default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  encoding: utf8mb4 
  collation: utf8mb4_unicode_ci
development:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] %>
test:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] %>
production:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] %>
